name: Event Builder Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to checkout when cutting the release."
        required: true
        default: "master"
      increment-major:
        description: "Should we increment the major version"
        required: true
        default: "false"
      increment-minor:
        description: "Should we increment the minor version"
        required: true
        default: "false"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Java Maven release
      uses: qcastel/github-actions-maven-release@v1.12.15
      env:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk/
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
        version-major: ${{ github.event.inputs.increment-major }}
        version-minor: ${{ github.event.inputs.increment-minor }}
        gpg-enabled: "true"
        gpg-key-id: ${{ secrets.GPG_KEY_ID }}
        gpg-key: ${{ secrets.GPG_KEY }}
        gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }} 
        maven-repo-server-id: ossrh
        maven-repo-server-username: ${{ secrets.NEXUS_USER }}
        maven-repo-server-password: ${{ secrets.NEXUS_PASSWORD }}
